package fr.dabsunter.clitem;

public enum ClickType {
	
	CLICK,
	INVENTORY_CLICK,
	INVENTORY_LEFT_CLICK,
	INVENTORY_RIGHT_CLICK,
	LEFT_CLICK,
	LEFT_CLICK_BLOCK,
	LEFT_CLICK_ENTITY,
	RIGHT_CLICK,
	RIGHT_CLICK_BLOCK,
	RIGHT_CLICK_ENTITY

}
